--- #YAML:1.0
name:                Tk-FlatCheckbox
version:             0.08
abstract:            an alternative checkbutton implementation for perl/Tk
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Tk:                            0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Slaven Rezic <srezic@cpan.org>
