---
abstract: 'an alternative checkbutton implementation for perl/Tk'
author:
  - 'Slaven Rezic <srezic@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120530'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tk-FlatCheckbox
no_index:
  directory:
    - t
    - inc
requires:
  Tk: 0
resources:
  repository: git://github.com/eserte/tk-flatcheckbox.git
version: 0.09
